# Gereral & Layout & Gestures.
# source = ~/.config/hypr/conf/general.conf
# Vrr & Xwayland.
# source = ~/.config/hypr/conf/misc.conf
# Decorations: rounding, blur, opacity.
# source = ~/.config/hypr/conf/decorations.conf
# Animations.
# source = ~/.config/hypr/conf/animations.conf

# Execute apps at launch.
source = ~/.config/hypr/conf/execs.conf
# Windowrules.
# source = ~/.config/hypr/conf/windowrules.conf
# Keybindings.
source = ~/.config/hypr/conf/keybinds.conf

@MONITOR_CONFIG@

xwayland {
    force_zero_scaling = true
}

@EXTRA_CONFIG@
