# https://wiki.hyprland.org/Configuring/Variables

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,preferred,auto,2

# See https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 2

    touchpad {
        natural_scroll = no
    }

    sensitivity = 0
}

# See https://wiki.hyprland.org/Configuring/Variables/#general
general {
    gaps_in = 4
    gaps_out = 8

    # gaps_workspaces = 50
    border_size = 1

    # col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    # col.inactive_border = rgba(595959aa)

    # col.active_border = rgba(2d2277ee)
    col.active_border = rgba(675ec5ee)
    col.inactive_border = rgba(474559cc)

    layout = dwindle
}

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = yes
    preserve_split = yes
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
}

# See https://wiki.hyprland.org/Configuring/Variables/ for more
gestures {
    workspace_swipe = off
}
