# https://wiki.hyprland.org/Configuring/Window-Rules

windowrulev2 = float        , class:(pavucontrol)
windowrulev2 = center       , class:(pavucontrol)
windowrulev2 = size 30% 50% , class:(pavucontrol)

windowrule = float        , ^(virt-manager)(.*)$
windowrule = center       , ^(virt-manager)(.*)$

windowrulev2 = float        , class:(thunar)
windowrulev2 = center       , class:(thunar)

windowrulev2 = size 30% 10% , class:(thunar), title:^(File Operation Progress)$
windowrulev2 = size 70% 70% , class:(thunar)

windowrulev2 = float        , class:(transmission-gtk)
windowrulev2 = size 50% 70% , class:(transmission-gtk)
windowrulev2 = center       , class:(transmission-gtk)

windowrule = float        , ^(mpv)(.*)$
windowrule = center       , ^(mpv)(.*)$

windowrule = float        , ^(org.fcitx)(.*)$
windowrule = center       , ^(org.fcitx)(.*)$

windowrulev2 = opacity 1.0 override, class:^(mpv)$
